### ISSUE TITLE
typo in file name Pizza.png

### ISSUE THREAD

**Issue by makanimike** [smeen89/Neapolitan-pizza-dough-calculator#1]
https://github.com/smeen89/Neapolitan-pizza-dough-calculator/blob/288224efc6a859d5676b9280215fa13dbefe328e/EN%20Lovelace%20UI%20card%20yaml%20code#L1

a small mistake in line 12 here. Either this should be 'Pizza.png', or the image file should be called 'pizza.png'.

**Comment by makanimike** [comment]
another tiny typo in line 821: RECIPE not RECIPEE

**Comment by csschef** [comment]
> https://github.com/smeen89/Neapolitan-pizza-dough-calculator/blob/288224efc6a859d5676b9280215fa13dbefe328e/EN%20Lovelace%20UI%20card%20yaml%20code#L1
> 
> a small mistake in line 12 here. Either this should be 'Pizza.png', or the image file should be called 'pizza.png'.



> another tiny typo in line 821: RECIPE not RECIPEE

Thank you! Both mistakes are corrected now!

**Comment by csschef** [comment]
Closing this issue
